apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: beeshoes-fe-autoscaling
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: deployment
    name: beeshoes-fe
  minReplicas: 1
  maxReplicas: 2
  targetCPUUtilizationPercentage: 50 # Over 50% use CPU -> Scaling 