global:
  imageRegistry: "harbor.deploy.io.vn"
  pullSecret: "harbor-secret"
  domain:
    frontend: "beeshoes.deploy.io.vn"
    backend: "api-beeshoes.deploy.io.vn"
beeshoes-backend:
  image:
    repository: "beeshoes/beeshoes-backend"
    tag: "v6.0-dev-6e2f6c6c"
  config:
    CLIENT_DOMAIN: "https://beeshoes.deploy.io.vn"
    REACT_APP_API_URL: "https://api-beeshoes.deploy.io.vn"
beeshoes-frontend:
  image:
    repository: "beeshoes/beeshoes-frontend"
    tag: "v6.0-dev-6e2f6c6c"
db:
  initImage:
    repository: "beeshoes/beeshoes-db-init"
    tag: "v1"
  dbImage: bitnami/mariadb:11.4.7
