apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: beeshoes-db-pvc
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-6"
    argocd.argoproj.io/sync-wave: "0"
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-storage-retain
  resources:
    requests:
      storage: 1Gi
