apiVersion: v1
kind: Service
metadata:
  name: beeshoes-db-service
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-6"
    argocd.argoproj.io/sync-wave: "1"
spec:
  selector:
    app: beeshoes-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
