apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv
spec:
  capacity: 
    storage: {{ .Values.storage }}
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: {{ .Values.hostPath | quote}}
