apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: beeshoes-be-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  ingressClassName: nginx
  rules:
    - host: {{ .Values.global.domain.backend }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: beeshoes-be-service
                port:
                  number: 8080
