global:
  imageRegistry: ""
  host: ""
backend:
  image:
    repository: "three_tier_app/backend"
    tag: e00f9c5e
    pullPolicy: Always
frontend:
  backend_url: ""
  image:
    repository: "three_tier_app/frontend"
    tag: e00f9c5e
    pullPolicy: Always
mongodb:
  image: mongo:4.4.6
  username: admin
  password: password123
  storage: 1Gi
  hostPath: /data/db
beeshoes-backe:
  image:
    tag: v1.7-dev-84ab418d
d:
  image:
    tag: v1.7-dev-84ab418d
beeshoes-fro:
  image:
    tag: v1.7-dev-84ab418d
te:
  image:
    tag: v1.7-dev-84ab418d
beeshoes-backend:
  image:
    tag: v2.9-dev-d49661b6
beeshoes-frontend:
  image:
    tag: v2.9-dev-d49661b6
