global:
  imageRegistry: ""
  host: ""
backend:
  image:
    repository: "three_tier_app/backend"
    tag: 183f1c64
    pullPolicy: Always
frontend:
  backend_url: ""
  image:
    repository: "three_tier_app/frontend"
    tag: 183f1c64
    pullPolicy: Always
mongodb:
  image: mongo:4.4.6
  username: admin
  password: password123
  storage: 1Gi
  hostPath: /data/db
