global:
  imageRegistry: ""

backend:
  image:
    repository: "three_tier_app/backend"
    tag: 8b629682
    pullPolicy: Always

frontend:
  image:
    repository: "three_tier_app/frontend"
    tag: 8b629682
    pullPolicy: Always  