apiVersion: v1
kind: Service
metadata:
  name: beeshoes-db-service
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-6"
spec:
  selector:
    app: beeshoes-db
  ports:
    - protocol: TCP
      port: 3306
      targetPort: 3306
  type: ClusterIP
