apiVersion: v1
kind: Secret
metadata:
  name: beeshoes-be-secret
type: Opaque
stringData:
    # Database
    DB_URL: "jdbc:mariadb://beeshoes-db-service:3306/beeshoes"
    DB_USERNAME: "beeshoes"
    DB_PASSWORD: "StrongPa55WorD"
    DB_INIT_DATABASE: "beeshoes"
    # Cloudinary
    CLOUDINARY_NAME: "username"
    CLOUDINARY_API_KEY: "apikey"
    CLOUDINARY_API_SECRET: "secret"
    # Email
    MAIL_HOST: "smtp.gmail.com"
    MAIL_PORT: "587"
    MAIL_USERNAME: "beesneakerfpthn@gmail.com"
    MAIL_PASSWORD: "xqamjohvbictleez"
    # JWT
    JWT_SECRET: "QHMBQfsViR66wU3Yx/MOdkKcHdmJeRy4JdbDbrjmZdfu35Q7yzH6b3vJCrQcNgoOEFfsGyhOeF5Pby7R+YzG0w=="
    # Config
    CLIENT_DOMAIN: "{{ .Values.config.CLIENT_DOMAIN }}"
    # env fe
    REACT_APP_API_URL: "{{ .Values.config.REACT_APP_API_URL }}"



